#!/usr/bin/env python3.8

import sys

from rqt_innoplot.module import MyPlugin
from rqt_gui.main import Main

plugin = 'rqt_innoplot'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
